# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: bookmaker 0.7.0.pre4 ruby lib

Gem::Specification.new do |s|
  s.name = "bookmaker"
  s.version = "0.7.0.pre4"

  s.required_rubygems_version = Gem::Requirement.new("> 1.3.1") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Merovex"]
  s.date = "2015-12-22"
  s.description = "Bookmaker provides authors a free, ruby-based production toolchain for self-published paper and electronic books using the LaTeX document preparation system."
  s.email = ["dausha+bookmaker@gmail.com"]
  s.executables = ["bookmaker"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".gitignore",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/bookmaker",
    "bookmaker.gemspec",
    "lib/bookmaker.rb",
    "lib/bookmaker/adapters/markdown.rb",
    "lib/bookmaker/cli.rb",
    "lib/bookmaker/dependency.rb",
    "lib/bookmaker/exporter.rb",
    "lib/bookmaker/extensions/string.rb",
    "lib/bookmaker/generator.rb",
    "lib/bookmaker/parser.rb",
    "lib/bookmaker/parser/epub.rb",
    "lib/bookmaker/parser/html.rb",
    "lib/bookmaker/parser/mobi.rb",
    "lib/bookmaker/parser/pdf.rb",
    "lib/bookmaker/stats.rb",
    "lib/bookmaker/stream.rb",
    "lib/bookmaker/toc.rb",
    "lib/bookmaker/toc/epub.rb",
    "lib/bookmaker/toc/html.rb",
    "lib/bookmaker/version.rb",
    "templates/config.erb",
    "templates/cover.jpg",
    "templates/dp-logo.png",
    "templates/epub/back.erb",
    "templates/epub/copyright.erb",
    "templates/epub/cover.erb",
    "templates/epub/cover.html",
    "templates/epub/page.erb",
    "templates/epub/user.css",
    "templates/extras.tex",
    "templates/html/copyright.erb",
    "templates/html/layout.css",
    "templates/html/layout.erb",
    "templates/html/syntax.css",
    "templates/html/thanks.erb",
    "templates/html/user.css",
    "templates/latex.erb",
    "templates/pdf/layout.erb",
    "templates/rakefile.rb",
    "templates/sample.tex",
    "test/helper.rb",
    "test/test_bookmaker.rb"
  ]
  s.homepage = "https://github.com/Merovex/bookmaker"
  s.rubyforge_project = "bookmaker"
  s.rubygems_version = "2.2.2"
  s.summary = "Bookmaker is a Ruby & LaTeX based production toolchain for self-publishers."
  s.test_files = ["test/helper.rb", "test/test_bookmaker.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<aruba>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_runtime_dependency(%q<rubyzip>, [">= 0"])
      s.add_runtime_dependency(%q<zip-zip>, [">= 0"])
      s.add_runtime_dependency(%q<eeepub>, [">= 0"])
      s.add_runtime_dependency(%q<kramdown>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<notifier>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<aruba>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rubyzip>, [">= 0"])
      s.add_dependency(%q<zip-zip>, [">= 0"])
      s.add_dependency(%q<eeepub>, [">= 0"])
      s.add_dependency(%q<kramdown>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<notifier>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<aruba>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rubyzip>, [">= 0"])
    s.add_dependency(%q<zip-zip>, [">= 0"])
    s.add_dependency(%q<eeepub>, [">= 0"])
    s.add_dependency(%q<kramdown>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<notifier>, [">= 0"])
  end
end

