# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: verku 0.8.1.0 ruby lib

Gem::Specification.new do |s|
  s.name = "verku"
  s.version = "0.8.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Merovex"]
  s.date = "2016-06-19"
  s.description = "Verku provides authors a free, ruby-based production toolchain for self-published paper and electronic books using the LaTeX document preparation system."
  s.email = ["dausha+verku@gmail.com"]
  s.executables = ["verku"]
  s.extra_rdoc_files = [
    "LICENSE.md",
    "README.md"
  ]
  s.files = [
    ".document",
    ".gitignore",
    ".rvmrc",
    "BUILD.md",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.md",
    "README.md",
    "Rakefile",
    "VERSION",
    "bin/verku",
    "lib/verku.rb",
    "lib/verku/adapters/markdown.rb",
    "lib/verku/cli.rb",
    "lib/verku/dependency.rb",
    "lib/verku/exporter.rb",
    "lib/verku/extensions/string.rb",
    "lib/verku/generator.rb",
    "lib/verku/parser.rb",
    "lib/verku/parser/epub.rb",
    "lib/verku/parser/html.rb",
    "lib/verku/parser/mobi.rb",
    "lib/verku/parser/pdf.rb",
    "lib/verku/parser/txt.rb",
    "lib/verku/stats.rb",
    "lib/verku/stream.rb",
    "lib/verku/toc.rb",
    "lib/verku/toc/epub.rb",
    "lib/verku/toc/html.rb",
    "lib/verku/version.rb",
    "templates/config.erb",
    "templates/cover.jpg",
    "templates/dp-logo.png",
    "templates/epub/back.erb",
    "templates/epub/copyright.erb",
    "templates/epub/cover.erb",
    "templates/epub/cover.html",
    "templates/epub/page.erb",
    "templates/epub/user.css",
    "templates/extras.tex",
    "templates/html/copyright.erb",
    "templates/html/layout.css",
    "templates/html/layout.erb",
    "templates/html/syntax.css",
    "templates/html/thanks.erb",
    "templates/html/user.css",
    "templates/latex.erb",
    "templates/merovex-logo.jpg",
    "templates/merovex-logo.png",
    "templates/pdf/layout.erb",
    "templates/rakefile.rb",
    "templates/readme.erb",
    "templates/text/01-Getting-Started.md",
    "templates/text/02-Creating-Chapters.md",
    "templates/text/03-Generating-Output.md",
    "templates/text/10-Test-Markdown.md",
    "test/helper.rb",
    "test/test_bookmaker.rb",
    "verku.gemspec"
  ]
  s.homepage = "https://github.com/Merovex/verku"
  s.rubyforge_project = "verku"
  s.rubygems_version = "2.2.2"
  s.summary = "Verku is a Ruby & LaTeX based production toolchain for self-publishers."
  s.test_files = ["test/helper.rb", "test/test_bookmaker.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_development_dependency(%q<simplecov>, [">= 0"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<aruba>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_runtime_dependency(%q<rubyzip>, [">= 0"])
      s.add_runtime_dependency(%q<zip-zip>, [">= 0"])
      s.add_runtime_dependency(%q<eeepub>, [">= 0"])
      s.add_runtime_dependency(%q<kramdown>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
      s.add_runtime_dependency(%q<notifier>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<rdoc>, ["~> 3.12"])
      s.add_dependency(%q<bundler>, ["~> 1.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
      s.add_dependency(%q<simplecov>, [">= 0"])
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<aruba>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<rubyzip>, [">= 0"])
      s.add_dependency(%q<zip-zip>, [">= 0"])
      s.add_dependency(%q<eeepub>, [">= 0"])
      s.add_dependency(%q<kramdown>, [">= 0"])
      s.add_dependency(%q<thor>, [">= 0"])
      s.add_dependency(%q<nokogiri>, [">= 0"])
      s.add_dependency(%q<notifier>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<rdoc>, ["~> 3.12"])
    s.add_dependency(%q<bundler>, ["~> 1.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0.1"])
    s.add_dependency(%q<simplecov>, [">= 0"])
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<aruba>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<rubyzip>, [">= 0"])
    s.add_dependency(%q<zip-zip>, [">= 0"])
    s.add_dependency(%q<eeepub>, [">= 0"])
    s.add_dependency(%q<kramdown>, [">= 0"])
    s.add_dependency(%q<thor>, [">= 0"])
    s.add_dependency(%q<nokogiri>, [">= 0"])
    s.add_dependency(%q<notifier>, [">= 0"])
  end
end

